# name: Housekeeping

# on:
#   push:
#     branches:
#       - master # Modify if you use a different main branch name, such as the legacy "master" name.
#   pull_request:
#     branches:
#       - master # Modify if you use a different main branch name, such as the legacy "master" name.

# jobs:
#   linting:
#     name: "Markdown linting"
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         name: Check out the code
#       - name: Lint Code Base
#         uses: docker://avtodev/markdown-lint:v1
#         with:
#           args: "**/*.md"
